version: '3.4'

services:
  nginx:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
      target: nginx
      args:
        ENV_FILE: .env.prod.dist
    ports:
      - published: 8081
        target: 80
        protocol: tcp
        mode: host
