version: '3.4'

services:
  nginx:
    image: quay.io/knplabs/keskonmange:nginx-${IMAGE_TAG:-dev}
    build:
      context: ./
      dockerfile: .docker/Dockerfile
      target: nginx
      args:
        ENV_FILE: .env.prod.dist
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`keskonmange.knpnet.net`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.docker.network=traefik"
    networks:
      - traefik

  reverse-proxy:
    image: quay.io/knplabs/keskonmange:reverse-proxy-${IMAGE_TAG:-dev}
    build:
      context: ./
      dockerfile: .docker/Dockerfile
      target: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik
