version: '3.4'

services:
  app:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
      target: dev
    command: 'yarn start'
    tty: true
    volumes:
      - ./:/app
    ports:
      - published: 3001
        target: 3000
        protocol: tcp
        mode: host
