version: 2

reference:
  vm_machine: &vm_machine
    working_directory: ~/keskonmang
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

jobs:
  test:
    working_directory: ~/keskonmang
    docker:
      - image: circleci/node:11.10.1-stretch
    environment:
      - NODE_ENV: "test"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install NodeJS dependencies
          command: 'yarn install'
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: 'Run tests'
          command: 'yarn test --runInBand'

workflows:
  version: 2

  test:
    jobs:
      - test:
          filters:
            branches: { ignore: master }
